### ISSUE TITLE
WebC fails with 11ty running on Deno

### ISSUE THREAD

**Issue by tryoxiss** [11ty/eleventy-plugin-webc#104]
(I'm not sure if Deno is officially supported, but I assume it is here as this is an official plugin for 11ty, where deno is officially supported)

When trying to build webc files on deno, dynamic attributes raise  errors.

Error logs:
```
website → deno task dev
Task dev eleventy --serve --incremental
[11ty] Problem writing Eleventy templates:
[11ty] 1. Having trouble rendering webc template ./_source/da/posts/index.webc (via TemplateContentRenderError)
[11ty] 2. Check the dynamic attribute: `webc:for="pagination.items"`.
[11ty] Original error message: Not implemented: createContext
[11ty] 
[11ty] Original error stack trace: Error: Check the dynamic attribute: `webc:for="pagination.items"`.
[11ty] Original error message: Not implemented: createContext
[11ty]     at Function.evaluateScript (file:///home/madeline/projects/website/node_modules/.deno/@11ty+webc@0.11.4/node_modules/@11ty/webc/src/moduleScript.cjs:71:10)
[11ty]     at Function.evaluateScriptInline (file:///home/madeline/projects/website/node_modules/.deno/@11ty+webc@0.11.4/node_modules/@11ty/webc/src/moduleScript.cjs:44:23)
[11ty]     at AstSerializer.evaluateAttribute (file:///home/madeline/projects/website/node_modules/.deno/@11ty+eleventy-plugin-webc@0.11.2/node_modules/@11ty/webc/src/ast.js:787:40)
[11ty]     at AstSerializer.getLoopContent (file:///home/madeline/projects/website/node_modules/.deno/@11ty+eleventy-plugin-webc@0.11.2/node_modules/@11ty/webc/src/ast.js:963:32)
[11ty]     at AstSerializer.compileNode (file:///home/madeline/projects/website/node_modules/.deno/@11ty+eleventy-plugin-webc@0.11.2/node_modules/@11ty/webc/src/ast.js:1006:26)
[11ty]     at AstSerializer.getChildContent (file:///home/madeline/projects/website/node_modules/.deno/@11ty+eleventy-plugin-webc@0.11.2/node_modules/@11ty/webc/src/ast.js:349:67)
[11ty]     at async AstSerializer.compileNode (file:///home/madeline/projects/website/node_modules/.deno/@11ty+eleventy-plugin-webc@0.11.2/node_modules/@11ty/webc/src/ast.js:1226:36)
[11ty]     at async AstSerializer.getChildContent (file:///home/madeline/projects/website/node_modules/.deno/@11ty+eleventy-plugin-webc@0.11.2/node_modules/@11ty/webc/src/ast.js:349:56)
[11ty]     at async AstSerializer.compileNode (file:///home/madeline/projects/website/node_modules/.deno/@11ty+eleventy-plugin-webc@0.11.2/node_modules/@11ty/webc/src/ast.js:1226:36)
[11ty]     at async AstSerializer.getChildContent (file:///home/madeline/projects/website/node_modules/.deno/@11ty+eleventy-plugin-webc@0.11.2/node_modules/@11ty/webc/src/ast.js:349:56)
[11ty] Wrote 0 files in 0.55 seconds (v3.0.0)
 website → 
```

Details:
- Deno 1.40.3
- `eleventy 3.0.0`
- `eleventy-plugin-webc ^0.11.2`

**Comment by ZenTrait** [comment]
a similar error occurs when I try to change the value of a @prop in --serve mode (if the page is not open in the browser, the error does not occur)

```
// _components/my_component.webc
<b @text="prop"></b>

// index.webc
<my-component @prop="Hello"></my-component>

```
```
[11ty] Unhandled rejection in promise:
[11ty] Is a directory (os error 21): readfile ''
[11ty] 
[11ty] Original error stack trace: Error: Is a directory (os error 21): readfile ''
[11ty]     at Object.readFileSync (ext:deno_fs/30_fs.js:733:10)
[11ty]     at Object.readFileSync (ext:deno_node/_fs/_fs_readFile.ts:52:21)
[11ty]     at EleventyDevServer._getFileContents (file:///home/zen_trait/.cache/deno/npm/registry.npmjs.org/@11ty/eleventy-dev-server/2.0.4/server.js:353:23)
[11ty]     at EleventyDevServer.eleventyDevServerMiddleware (file:///home/zen_trait/.cache/deno/npm/registry.npmjs.org/@11ty/eleventy-dev-server/2.0.4/server.js:506:29)
[11ty]     at EleventyDevServer.onRequestHandler (file:///home/zen_trait/.cache/deno/npm/registry.npmjs.org/@11ty/eleventy-dev-server/2.0.4/server.js:633:11)
[11ty]     at ServerImpl.emit (ext:deno_node/_events.mjs:393:28)
[11ty]     at node:http:1316:16
[11ty]     at new Promise (<anonymous>)
[11ty]     at handler (node:http:1314:16)
[11ty]     at ext:deno_http/00_serve.ts:369:24
fish: Job 1, 'deno run -A npm:@11ty/eleventy@…' terminated by signal SIGTERM (Polite quit request)

```
