### ISSUE TITLE
How to add new bundle types while using eleventy-plugin-webc?

### ISSUE THREAD

**Issue by awmottaz** [11ty/eleventy-plugin-webc#106]
If I do not use this plugin, I can use custom bundle types, no problem. This is a working example:

```js
// eleventy.config.js

export default function(eleventyConfig) {
  eleventyConfig.addBundle("foo");
}
```

```
<!-- index.html -->

{% foo %}
    Bundled stuff goes here
{% endfoo %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
  </head>
  <body>
    <output>{% getBundle "foo" %}</output>
  </body>
</html>
```

The build output is:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
  </head>
  <body>
    <output>Bundled stuff goes here</output>
  </body>
</html>
```

If I add the WebC plugin and change nothing else, now my custom bundle identifier is "invalid":

```js
// eleventy.config.js

import pluginWebc from "@11ty/eleventy-plugin-webc";

export default function(eleventyConfig) {
  eleventyConfig.addPlugin(pluginWebc);
  eleventyConfig.addBundle("foo")
};
```

Same input files, running a build produces this error:

```
[11ty] Problem writing Eleventy templates:
[11ty] 1. Having trouble rendering liquid template ./index.html (via TemplateContentRenderError)
[11ty] 2. Invalid bundle type: foo, file:./index.html, line:12, col:13 (via RenderError)
[11ty] 3. Invalid bundle type: foo
[11ty] 
[11ty] Original error stack trace: Error: Invalid bundle type: foo
[11ty]     at Object.getContent ([project-root-redacted]/node_modules/@11ty/eleventy-plugin-webc/node_modules/@11ty/eleventy-plugin-bundle/eleventy.shortcodes.js:47:10)
[11ty]     at Object.fn (file://[project-root-redacted]/node_modules/@11ty/eleventy/src/Benchmark/BenchmarkGroup.js:37:23)
[11ty]     at Tag.render (file://[project-root-redacted]/node_modules/@11ty/eleventy/src/Engines/Liquid.js:218:34)
[11ty]     at render.next (<anonymous>)
[11ty]     at toPromise ([project-root-redacted]/node_modules/liquidjs/dist/liquid.node.js:524:32)
[11ty]     at async toPromise ([project-root-redacted]/node_modules/liquidjs/dist/liquid.node.js:532:25)
[11ty]     at async toPromise ([project-root-redacted]/node_modules/liquidjs/dist/liquid.node.js:532:25)
[11ty]     at async Template._render (file://[project-root-redacted]/node_modules/@11ty/eleventy/src/TemplateContent.js:608:19)
[11ty]     at async TemplateMap.populateContentDataInMap (file://[project-root-redacted]/node_modules/@11ty/eleventy/src/TemplateMap.js:545:7)
[11ty]     at async TemplateMap.cache (file://[project-root-redacted]/node_modules/@11ty/eleventy/src/TemplateMap.js:451:3)
[11ty] Wrote 0 files in 0.09 seconds (v3.0.0)
```

Using

- `@11ty/eleventy@v3.0.0`
- `@11ty/eleventy-plugin-webc@0.11.2`

Apologies if I'm submitting this issue to the wrong repository, it appears to me like the bundle plugin is working correctly and it's the WebC plugin that's causing the error. Let me know if that's not the case.

**Comment by awmottaz** [comment]
Update: this appears to be fixed in the 0.12 beta 🥳
