### ISSUE TITLE
shortCode inaccessible in template webc:type="11ty"

### ISSUE THREAD

**Issue by khalidabuhakmeh** [11ty/eleventy-plugin-webc#16]
I was converting a `liquid` template over to `webC` but could not access a custom shortcode. This same liquid template works in a `.liquid` file unchanged.

```javascript
    eleventyConfig.addShortcode("possum_link", function(slug) {
        return `/possums/${slug}/`
    });
```

```html
---
layout: layout.liquid
---

<h1 @html="title"></h1>

<p>I want to say something right now</p>

<template webc:type="11ty" 11ty:type="liquid">
<ul class="nes-list is-disc">
    {% for possum in possums %}
        <li>
            <a href="{% possum_link possum.slug %}">
                {{ possum.name }}
            </a>
        </li>
    {% endfor %}
</ul>
</template>

<twitter-share></twitter-share>
```

```console
[11ty] File changed: index.webc
[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] 1. Having trouble rendering webc template ./index.webc (via TemplateContentRenderError)
[11ty] 2. tag "possum_link" not found, file:liquid, line:5, col:22, file:liquid, line:3, col:5 (via ParseError)
[11ty] 3. tag "possum_link" not found, file:liquid, line:5, col:22 (via ParseError)
[11ty] 4. tag "possum_link" not found (via AssertionError)
[11ty] 
[11ty] Original error stack trace: AssertionError: tag "possum_link" not found
[11ty]     at new AssertionError (/Users/khalidabuhakmeh/WebstormProjects/eleventy-two-oh/node_modules/liquidjs/dist/liquid.node.cjs.js:1089:28)
[11ty]     at assert (/Users/khalidabuhakmeh/WebstormProjects/eleventy-two-oh/node_modules/liquidjs/dist/liquid.node.cjs.js:1124:15)
[11ty]     at TagMap.get (/Users/khalidabuhakmeh/WebstormProjects/eleventy-two-oh/node_modules/liquidjs/dist/liquid.node.cjs.js:4355:9)
[11ty]     at new Tag (/Users/khalidabuhakmeh/WebstormProjects/eleventy-two-oh/node_modules/liquidjs/dist/liquid.node.cjs.js:4177:32)
[11ty]     at Parser.parseToken (/Users/khalidabuhakmeh/WebstormProjects/eleventy-two-oh/node_modules/liquidjs/dist/liquid.node.cjs.js:4273:24)
[11ty]     at ParseStream.parseToken (/Users/khalidabuhakmeh/WebstormProjects/eleventy-two-oh/node_modules/liquidjs/dist/liquid.node.cjs.js:4286:80)
[11ty]     at ParseStream.start (/Users/khalidabuhakmeh/WebstormProjects/eleventy-two-oh/node_modules/liquidjs/dist/liquid.node.cjs.js:2386:33)
[11ty]     at Object.parse (/Users/khalidabuhakmeh/WebstormProjects/eleventy-two-oh/node_modules/liquidjs/dist/liquid.node.cjs.js:2718:16)
[11ty]     at new Tag (/Users/khalidabuhakmeh/WebstormProjects/eleventy-two-oh/node_modules/liquidjs/dist/liquid.node.cjs.js:4181:24)
[11ty]     at Parser.parseToken (/Users/khalidabuhakmeh/WebstormProjects/eleventy-two-oh/node_modules/liquidjs/dist/liquid.node.cjs.js:4273:24)
[11ty] Wrote 0 files in 0.03 seconds (v2.0.0-canary.16)
[11ty] Watching…
```

**Comment by rothsandro** [comment]
Custom filters don't work either (tested with njk).

**Comment by zachleat** [comment]
This will ship with Eleventy WebC v0.7.0
