### ISSUE TITLE
Regression with webc:type="11ty" `TemplateRenderConfigError` error

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy-plugin-webc#64]
Affects Eleventy 2.0.1+

```
[11ty] 1. Having trouble rendering webc template ./index.webc (via TemplateContentRenderError)
[11ty] 2. Missing `config` argument. (via TemplateRenderConfigError)
[11ty] 
[11ty] Original error stack trace: TemplateRenderConfigError: Missing `config` argument.
[11ty]     at new TemplateRender (/Users/zachleat/Code/eleventy/src/TemplateRender.js:19:13)
[11ty]     at compile (/Users/zachleat/Code/eleventy/src/Plugins/RenderPlugin.js:35:12)
[11ty]     at Object.<anonymous> (/Users/zachleat/Temp/eleventy-201-regression/node_modules/@11ty/eleventy-plugin-webc/src/eleventyWebcTemplate.js:107:21)
[11ty]     at AstSerializer.transformContent (file:///Users/zachleat/Temp/eleventy-201-regression/node_modules/@11ty/webc/src/ast.js:494:42)
[11ty]     at AstSerializer.getContentForTemplate (file:///Users/zachleat/Temp/eleventy-201-regression/node_modules/@11ty/webc/src/ast.js:612:15)
[11ty]     at AstSerializer.compileNode (file:///Users/zachleat/Temp/eleventy-201-regression/node_modules/@11ty/webc/src/ast.js:1148:24)
[11ty]     at async AstSerializer.getChildContent (file:///Users/zachleat/Temp/eleventy-201-regression/node_modules/@11ty/webc/src/ast.js:347:56)
[11ty]     at async AstSerializer.compileNode (file:///Users/zachleat/Temp/eleventy-201-regression/node_modules/@11ty/webc/src/ast.js:1170:36)
[11ty]     at async AstSerializer.getChildContent (file:///Users/zachleat/Temp/eleventy-201-regression/node_modules/@11ty/webc/src/ast.js:347:56)
[11ty]     at async AstSerializer.compileNode (file:///Users/zachleat/Temp/eleventy-201-regression/node_modules/@11ty/webc/src/ast.js:1170:36)
```

**Comment by zachleat** [comment]
Fixed by 69c7edfb8e5123febfc9ccba9f6eaeeb707cf388
