### ISSUE TITLE
Using permalink: false in .md fails with eleventy-plugin-webc plugin

### ISSUE THREAD

**Issue by mhaack** [11ty/eleventy-plugin-webc#9]
To reproduce:

* setup eleventy-plugin-webc on an existing project
* configure plugin with `useTransform: true`
* add `permalink: false` to a markdown frontmatter

Result:

```[dev:11ty] [11ty] Problem writing Eleventy templates: (more in DEBUG output)
[dev:11ty] [11ty] 1. Having trouble writing to "false" from "./src/home/contact.md" (via EleventyTemplateError)
[dev:11ty] [11ty] 2. Transform `@11ty/eleventy-plugin-webc` encountered an error when transforming ./src/home/contact.md. (via EleventyTransformError)
[dev:11ty] [11ty] 3. this.outputPath?.endsWith is not a function (via TypeError)
[dev:11ty] [11ty]
[dev:11ty] [11ty] Original error stack trace: TypeError: this.outputPath?.endsWith is not a function
[dev:11ty] [11ty]     at Object.<anonymous> (/Users/mhaack/workspaces/playground/mh-site/node_modules/@11ty/eleventy-plugin-webc/src/eleventyWebcTransform.js:11:79)
[dev:11ty] [11ty]     at Template.runTransforms (/Users/mhaack/workspaces/playground/mh-site/node_modules/@11ty/eleventy/src/Template.js:511:30)
[dev:11ty] [11ty]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[dev:11ty] [11ty]     at async Template.renderPageEntry (/Users/mhaack/workspaces/playground/mh-site/node_modules/@11ty/eleventy/src/Template.js:796:15)
[dev:11ty] [11ty]     at async /Users/mhaack/workspaces/playground/mh-site/node_modules/@11ty/eleventy/src/Template.js:816:21
[dev:11ty] [11ty]     at async Promise.all (index 0)
[dev:11ty] [11ty]     at async Promise.all (index 4)
[dev:11ty] [11ty]     at async Eleventy.executeBuild (/Users/mhaack/workspaces/playground/mh-site/node_modules/@11ty/eleventy/src/Eleventy.js:1121:13)
[dev:11ty] [11ty]     at async Eleventy.watch (/Users/mhaack/workspaces/playground/mh-site/node_modules/@11ty/eleventy/src/Eleventy.js:937:18)
[dev:11ty] [11ty] Wrote 0 files in 34.99 seconds (v2.0.0-canary.16)
[dev:11ty] error Command failed with exit code 1.
[dev:11ty] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by zachleat** [comment]
This fix will ship in v0.5.0!
